config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                     }
  root "letters#index"
  resources :users, only: [:new, :show]
  resources :letters, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user

  validates :text, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :sns_credentials
  has_many :letters

  validates :name, presence: true

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  def index
  end

  def new
    @letter = Letter.new
  end

  def create
    @letter = Letter.create(letter_params)
    if @letter.save
    else
      render :new
    end
  end

  def show
  end

  private

  def letter_params
    params.require(:letter).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]
    if @user.persisted? # ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else # ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @letters = user.letters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neneletter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <%= yield %>
  <footer class="ui center aligned basic segment" style="margin-top: 1em;">
    <div class="ui center aligned grid">
      <div data-tooltip="facebookでシェアする" data-position="top left" data-inverted data-variation="mini" class="ui facebook small icon circular button">
        <i class="facebook icon"></i>
      </div>
      <div data-tooltip="Twitterでシェアする" data-position="top left" data-inverted data-variation="mini" class="ui twitter small icon circular button">
        <i class="twitter icon"></i>
      </div>
    </div>
    <div class="ui basic segment">
      <p>カバー株式会社様、およびホロライブプロダクションとは⼀切関係ありません。</p>
      <p>当サイトで使⽤している画像の著作権・肖像権等は各権利者に帰属いたします。</p>
    </div>
  </footer>
  </body>
</html>

app/views/letters/create.html.erb
<div id="success">
  <div class="success">
    <h3>手紙の作成が完了しました。</h3>
    <div class="ui info message">
      <i class="close icon"></i>
      <div class="header">
        登録したメールアドレスに画像が届きますので、ご確認をお願いいたします
      </div>
      <ul class="list">
        <li>「info@neneletter.com」よりメールが届きます。</li>
        <li>画像完成までに3日程度かかりますので、ご了承ください。</li>
        <li>迷惑メールの対策などでドメイン指定を行っている場合、メールが受信できない場合がございます。<br>「@neneletter.com」を受信設定してください。</li>
      </ul>
    </div>
    <div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        発送について
      </div>
      <ul class="list">
        <li>発送は内容の校閲後、全て一斉に行います</li>
        <li>発送は8/6を予定しております</li>
        <li>詳しい日程については<%= link_to "運営者のTwitter", 'https://twitter.com/hedgehog_nene' %>より発表いたします</li>
      </ul>
    </div>
    <%= link_to "戻る", root_path %>
  </div>
</div>

app/views/letters/index.html.erb
<div id="top"class="ui inverted attached center aligned basic segment">
  <div id="headercontainer" class="ui text container">
    <h1 id="maintitle" class="ui massive center aligned header"><span id="subtitle" class="sub header">桃鈴ねね活動1周年記念企画</span><span id="maintitleheader">NeneLeter</span></h1>
    <% if user_signed_in? %>
      <div id="login" class="ui center aligned grid">
        <button class="ui blue button"><%= link_to '手紙を書く', new_letter_path , class:"linkto" %></button>
      </div>
    <% else %>
      <div id="login" class="ui center aligned grid">
        <% if user_signed_in? %>
          <button class="ui secondary button"><%= link_to '手紙を書く', new_letter_path, class:"linkto" %></button>
        <% else %>
          <button class="ui secondary button"><%= link_to '手紙を書く(手紙を書くにはログインが必要です)', new_user_registration_path, class:"linkto" %></button>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="main-content">
  <div class="ui center aligned grid">
  <% if user_signed_in? %>
    <button id="mypage" class="ui secondary button"><%= link_to 'マイページ', "/users/#{current_user.id}", class:"linkto" %></button>
  <% end %>
  </div>
  <h2 class="ui header" id="period">
  <i class="calendar check outline icon"></i>
  <div class="content">
    募集期間：7/18(日)~8/1(日) 23:59(JST)
  </div>
  </h2>
  <div class="ui piled segment">
    <h4 class="ui header">桃鈴ねね 活動1周年記念にファンレターを書きませんか？</h4>
    <p>この企画は桃鈴ねねちゃんの活動1周年を記念してファンレターを届けようという企画です。</p>
    <p>ファンレターというと、手書きで便箋を選んだり、発送先を調べて送ったり面倒なことが多く、今まで送ったことある人は少ないのではないのでしょうか？</p>
    <p>この企画では、便箋を選ぶ必要もなく、ただ文章を考えて、入力するだけで、ファンレターを作成することができます！</p>
    <p>面倒な発送作業などは当企画運営陣にて行いますので、ご安心ください！</p>
    <p>必要なものはGoogleアカウントのみ！海外の方もご利用いただけます。</p>
    <p>ぜひこの機会に大好きな桃鈴ねねちゃんにファンレターを書いて、日頃の感謝の気持ちを直接伝えよう！</p>
  </div>
  <div class="ui center aligned grid">
  <%= video_tag("/videos/ファンレター広告用動画.mp4", autoplay: :true, loop: :true, muted: :true,controls: :true,style:"width:50%;") %>
  </div>
  <div class="ui center aligned grid">
    <div id="step" class="ui large steps">
      <div class="step">
        <i class="users green icon"></i>
      <div class="content">
        <div class="title">会員登録する</div>
      </div>
      </div>
    <div class="step">
      <i class="payment teal icon"></i>
      <div class="content">
        <div class="title">フォーマットに合わせて手紙を書く</div>
      </div>
    </div>
      <div class="step">
      <i class="paper plane outline blue icon"></i>
      <div class="content">
        <div class="title">投稿する</div>
      </div>
    </div>
    </div>
  </div>
  <h2 class="ui center aligned icon header">
    <i class="users green icon"></i>
    <div class="content">
      <span id="h2_under_line">STEP1 会員登録する</span>
      <div class="sub header">
        <p>メールアドレスがあればOK<br>Googleアカウントがあれば面倒な登録は不要です</p>
      </div>
    </div>
  </h2>
  <h2 class="ui center aligned icon header">
    <i class="edit teal icon"></i>
    <div class="content">
      <span id="h2_under_line">STEP2 フォーマットに合わせて手紙を書く</span>
      <div class="sub header">
        <p>ペンや紙は一切不要<br>WEB上で文章を書けばそのまま手紙になってねねちに届きます</p>
      </div>
    </div>
  </h2>
  <h2 class="ui center aligned icon header">
    <i class="paper plane outline blue icon"></i>
    <div class="content">
      <span id="h2_under_line">STEP3 投稿する</span>
      <div class="sub header">
        <p>面倒な配送は一切不要</p>
      </div>
    </div>
  </h2>
  <h2 class="ui center aligned header"><span id="h2_under_line">FAQ</span></h2>
  <div class="ui icon message">
    <i class="money bill alternate outline teal icon"></i>
      <div class="content">
        <div class="header">
          料金は無料ですか？
        </div>
        <p>無料でご利用いただけます。</p>
      </div>
  </div>
  <div class="ui icon message">
  <i class="envelope open outline blue icon"></i>
  <div class="content">
    <div class="header">
      手紙の内容は公開されますか？
    </div>
    <p>公開はされませんが、送付前に誹謗中傷や政治、宗教に関する記述、個人情報の記述がないか、チェックさせていただき、送付いたします。</p>
  </div>
  </div>
    <div class="ui icon message">
    <i class="sign language teal icon"></i>
      <div class="content">
        <div class="header">
          海外からでも利用できますか？
        </div>
        <p>ご利用可能です。また投稿を行えば、発送は日本国内で行うため、面倒な発送手続きは不要です。</p>
      </div>
  </div>
  <div class="ui icon message">
  <i class="globe blue icon"></i>
  <div class="content">
    <div class="header">
      翻訳してもらうことは可能ですか？
    </div>
    <p>英語については翻訳可能です。その他言語も特定ができれば翻訳することは可能です。</p>
  </div>
  </div>
  <% if user_signed_in? %>
    <button id="mypage" class="ui secondary button"><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class:'btn' %></button>
  <% end %>
</div>

app/views/letters/new.html.erb
<div id="letteredit">
  <script>
    $(function() {
        $('#liveeditor').keyup(function() {
          //$('#livepreview').html(this.value.replace(/\n/g, '<br/>'));
          $('#livepreview').html($('#liveeditor').val());
        });
    });
  </script>
    <div class="ui mini steps">
      <div class="step">
        <i class="edit outline icon"></i>
        <div class="content">
          <div class="title">1.手紙を書く</div>
          <div class="description">テキスト入力欄にて<br>手紙を書いてください</div>
        </div>
      </div>
      <div class="step">
        <i class="envelope open outline icon"></i>
        <div class="content">
          <div class="title">2.送るボタンを押す</div>
          <div class="description">「送る」ボタンを押すと登録完了します</div>
        </div>
      </div>
      <div class="step">
        <i class="download icon"></i>
        <div class="content">
          <div class="title">3.メールアドレスに完成した画像が届く</div>
          <div class="description">登録した内容を元に手紙が作成され、<br>登録したメールアドレスに画像が届きます</div>
        </div>
      </div>
      <div class="step">
        <i class="upload icon"></i>
        <div class="content">
          <div class="title">4.画像がOKなら、送付されます</div>
          <div class="description">送付した手紙が問題なければ、<br>その内容でホロライブへ送付されます</div>
        </div>
      </div>
    </div>
    <div class="ui steps">
    <div class="step">
      <div class="title">STEP1 手紙を書く</div>
      <div class="description">テキスト入力欄にて手紙を書いてください</div>
    </div>
    </div>
    <br>
    <h2 class="ui header">
      <i class="eye icon"></i>
      <div class="content">
        完成図イメージ
      </div>
    </h2>
    <%= image_tag 'done.001.jpg', id: :livepreview %>
    <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      下記事項に該当する記載があった場合は削除させていただきます
    </div>
    <ul class="list">
      <li>住所や本名など個人情報</li>
      <li>Amazonギフト券などの金品のコード</li>
      <li>特定の人物、組織に対する誹謗中傷</li>
      <li>政治、宗教に関する事項</li>
    </ul>
    </div>
    <div class="ui success message">
      <i class="close icon"></i>
      <div class="header">
        文字数の制限について
      </div>
      <p>特に制限はありません。(テストで1万文字でも登録できることを確認しています)</p>
      <p>絵文字も使用できます。</p>
    </div>
    <div id="letter">
    <div class="ui form">
    <div class="field">
      <%= form_with(model: @letter, local: true) do |form| %>
        <%= form.text_area :text, placeholder: "ここに本文を記入", rows: "10",class: :form_text,id: :liveeditor %>
    </div>
    </div>
        <div class="ui steps">
          <div class="step">
            <div class="title">STEP2 送るボタンを押す</div>
            <div class="description">「送る」ボタンを押すと送信完了！</div>
          </div>
        </div>
        <div class="ui warning message">
          <div class="header">
          「送る」ボタンを押す前に確認してください
          </div>
          <ul class="list">
            <li>「送る」ボタンを押しても反応しない場合はブラウザをリロードしてください</li>
            <li>その際、入力済みのテキストが消えてしまうため、リロード前にコピーを忘れないでください</li>
            <li>手紙の内容に個人情報や金券の情報、誹謗中傷などの記載はないですか？</li>
            <li>翻訳を希望される場合はその旨を本文に記述をお願いします</li>
            <li>If you would like a translation, please state so in the text.</li>
          </ul>
        </div>
        <%= form.submit "送る",class:"massive ui secondary button" %>
        <% end %>
        <br>
        <div class="ui steps">
        <div class="step">
          <div class="title">STEP3 メールアドレスに完成した画像が届く</div>
          <div class="description">登録した内容を元に手紙が作成され、登録したメールアドレスに画像が届きます</div>
        </div>
        </div>
        <div class="ui steps">
        <div class="step">
          <div class="title">STEP4 画像がOKなら、送付されます</div>
          <div class="description">送付した手紙が問題なければ、その内容でホロライブへ送付されます</div>
        </div>
        </div>
        <br>
    </div>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <li><%= "#{current_user.name}でログイン中" %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
<% else %>
  <p>ログインしていません</p>
  <li><%= link_to 'ログイン', new_user_session_path %></li>
  <li><%= link_to '新規登録', new_user_path %></li>
<% end %>

app/views/users/new.html.erb
<%= link_to "メールアドレスで登録", new_user_registration_path%>
<%= link_to "Googleで登録", user_google_oauth2_omniauth_authorize_path, method: :post%>

app/views/users/show.html.erb
<div id="mypageshow">
  <div class="contents row">
    <div class="ui steps" id="mypageicon">
      <div class="step">
        <i class="smile outline icon"></i>
        <div class="content">
          <div class="title"><%= @name %>さんの手紙</div>
        </div>
      </div>
  </div>
    <% @letters.each do |letter| %>
      <div class="ui stacked segment">
        <h4 class="ui header">投稿日:<%= letter.created_at %></h4>
        <p><%= letter.text %></p>
      </div>
    <% end %>
  </div>
</div>